name: Deploy Calendar Free Time

on:
  schedule:
    # Run daily at 4:00 AM UTC
    - cron: "0 4 * * *"
  workflow_dispatch:
    # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create .env file with secrets
        run: |
          cat > .env << EOF
          CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
          PROJECT_NAME=${{ secrets.PROJECT_NAME }}
          CAL_URLS=(
            ${{ secrets.CAL_URLS }}
          )
          EOF

      - name: Make deploy script executable
        run: chmod +x deploy.sh

      - name: Run deploy script
        run: ./deploy.sh
